server:
  port: 7070 #服务注册中心端口号
eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心ip
  client:
    register-with-eureka: false #是否向服务注册中心注册自己
    fetch-registry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    #关闭自我保护机制，保证不可用服务被及时删除 true为开启 false为关闭
    enable-self-preservation: true
    #如果2s内没有收到某个服务的心跳，那就删除该微服务，单位是毫秒
    eviction-interval-timer-in-ms: 2000
