server:
  port: 8081
#eureka:
#  client:
#    serviceUrl: #服务注册中心接口地址
#      defaultZone: http://127.0.0.1:7070/eureka/
#  instance:
#    #心跳检测与续约时间（开发环境可以将值设置小一点，保障服务关闭后注册中心能及时将服务剔除）
#    lease-expiration-duration-in-seconds: 15
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会遵循规则）
#    lease-renewal-interval-in-seconds: 5

spring:
  application:
    name: mayikt-member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



